# Generated by Django 2.0.6 on 2018-10-14 06:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_auto_20181014_0923'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='clasroom',
            new_name='classroom',
        ),
    ]
